from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .models import AppState, FirewallConfig, FirewallRules


CHAIN_ORDER = ("input", "forward", "output")
CHAIN_LABELS = {
    "input": "Input",
    "forward": "Forward",
    "output": "Output",
}
PRESET_ORDER = ("basic", "recommended", "advanced")


RULE_METADATA: dict[str, dict[str, str]] = {
    "input_established_related": {
        "title": "Accept established/related",
        "description": "Lets the router keep valid traffic that is already in progress.",
        "chain": "input",
    },
    "input_drop_invalid": {
        "title": "Drop invalid packets",
        "description": "Removes broken or inconsistent traffic before it reaches services.",
        "chain": "input",
    },
    "input_allow_icmp": {
        "title": "Allow ICMP",
        "description": "Keeps ping and basic diagnostics available.",
        "chain": "input",
    },
    "input_allow_internal_management": {
        "title": "Allow management from internal networks",
        "description": "Allows the router to be reached from the bridge and VLAN interfaces.",
        "chain": "input",
    },
    "input_drop_wan_admin": {
        "title": "Block management from WAN",
        "description": "Drops unsolicited access from the internet to the router itself.",
        "chain": "input",
    },
    "input_port_scan_guard": {
        "title": "Port scan protection",
        "description": "Drops common TCP scan patterns arriving from WAN.",
        "chain": "input",
    },
    "input_bruteforce_guard": {
        "title": "SSH brute-force protection",
        "description": "Drops repeated SSH attempts from the WAN side.",
        "chain": "input",
    },
    "forward_established_related": {
        "title": "Accept established/related",
        "description": "Keeps valid forwarded sessions flowing between networks.",
        "chain": "forward",
    },
    "forward_drop_invalid": {
        "title": "Drop invalid packets",
        "description": "Filters broken forwarded traffic before it crosses networks.",
        "chain": "forward",
    },
    "forward_allow_internal_to_wan": {
        "title": "Allow internal traffic to WAN",
        "description": "Allows bridge and VLAN networks to reach the internet.",
        "chain": "forward",
    },
    "forward_allow_dstnat": {
        "title": "Allow dstnat traffic",
        "description": "Keeps intentional port forwards working when they exist.",
        "chain": "forward",
    },
    "forward_isolate_vlans": {
        "title": "Isolate VLANs and internal segments",
        "description": "Blocks traffic between internal networks unless another rule allows it first.",
        "chain": "forward",
    },
    "forward_drop_new_wan": {
        "title": "Drop new WAN-to-LAN traffic",
        "description": "Rejects unsolicited new sessions coming from WAN.",
        "chain": "forward",
    },
    "output_established_related": {
        "title": "Accept established/related",
        "description": "Keeps router-originated reply traffic consistent.",
        "chain": "output",
    },
    "output_drop_invalid": {
        "title": "Drop invalid packets",
        "description": "Drops invalid traffic generated by local router processes.",
        "chain": "output",
    },
    "nat_masquerade": {
        "title": "NAT masquerade on WAN",
        "description": "Translates internal traffic to the WAN address.",
        "chain": "forward",
    },
    "raw_block_dns_wan": {
        "title": "Early DNS drop on WAN (v7)",
        "description": "Drops WAN DNS requests early in the raw table on RouterOS v7.",
        "chain": "input",
    },
    "log_wan_drops": {
        "title": "Log WAN drops",
        "description": "Adds visibility for dropped WAN input and unsolicited WAN forwarding.",
        "chain": "input",
    },
}


PRESET_DETAILS = {
    "basic": {
        "title": "Basico",
        "includes": [
            "Established/related and invalid hygiene",
            "ICMP and management from internal networks",
            "Administrative block on WAN",
            "Internal traffic to WAN and dstnat support",
            "Masquerade on WAN",
        ],
    },
    "recommended": {
        "title": "Recomendado",
        "includes": [
            "Everything in Basico",
            "Port scan and SSH brute-force protection",
            "VLAN and internal network isolation",
            "Output chain hygiene",
        ],
    },
    "advanced": {
        "title": "Avancado",
        "includes": [
            "Everything in Recomendado",
            "Logging for dropped WAN traffic",
            "Raw DNS drop for RouterOS v7",
        ],
    },
}


@dataclass(frozen=True)
class FirewallEntry:
    section: str
    label: str
    comment: str
    params: dict[str, Any]


def normalize_preset_name(preset: str) -> str:
    if preset == "medium":
        return "recommended"
    if preset not in PRESET_DETAILS:
        return "basic"
    return preset


def get_preset_title(preset: str) -> str:
    return PRESET_DETAILS[normalize_preset_name(preset)]["title"]


def build_firewall_rules(preset: str) -> FirewallRules:
    normalized = normalize_preset_name(preset)
    rules = FirewallRules()

    if normalized in {"recommended", "advanced"}:
        rules.input_port_scan_guard = True
        rules.input_bruteforce_guard = True
        rules.forward_isolate_vlans = True
        rules.output_established_related = True
        rules.output_drop_invalid = True

    if normalized == "advanced":
        rules.raw_block_dns_wan = True
        rules.log_wan_drops = True

    return rules


def build_firewall_config(preset: str) -> FirewallConfig:
    normalized = normalize_preset_name(preset)
    return FirewallConfig(preset=normalized, rules=build_firewall_rules(normalized))


def build_firewall_entries(state: AppState, version_folder: str) -> list[FirewallEntry]:
    wan_iface = state.get_wan_interface()
    if not wan_iface:
        return []

    rules = state.firewall.rules
    entries: list[FirewallEntry] = []
    internal_ifaces = _internal_interfaces(state)

    if rules.input_established_related:
        entries.append(
            _filter_entry(
                "Accept established input",
                "mtk-auto input established",
                chain="input",
                **{"connection-state": "established,related", "action": "accept"},
            )
        )
    if rules.forward_established_related:
        entries.append(
            _filter_entry(
                "Accept established forward",
                "mtk-auto forward established",
                chain="forward",
                **{"connection-state": "established,related", "action": "accept"},
            )
        )
    if rules.output_established_related:
        entries.append(
            _filter_entry(
                "Accept established output",
                "mtk-auto output established",
                chain="output",
                **{"connection-state": "established,related", "action": "accept"},
            )
        )

    if rules.input_drop_invalid:
        entries.append(
            _filter_entry(
                "Drop invalid input",
                "mtk-auto input invalid",
                chain="input",
                **{"connection-state": "invalid", "action": "drop"},
            )
        )
    if rules.forward_drop_invalid:
        entries.append(
            _filter_entry(
                "Drop invalid forward",
                "mtk-auto forward invalid",
                chain="forward",
                **{"connection-state": "invalid", "action": "drop"},
            )
        )
    if rules.output_drop_invalid:
        entries.append(
            _filter_entry(
                "Drop invalid output",
                "mtk-auto output invalid",
                chain="output",
                **{"connection-state": "invalid", "action": "drop"},
            )
        )

    if rules.input_allow_icmp:
        entries.append(
            _filter_entry(
                "Allow ICMP",
                "mtk-auto allow icmp",
                chain="input",
                protocol="icmp",
                action="accept",
            )
        )

    if rules.input_allow_internal_management:
        for iface in internal_ifaces:
            entries.append(
                _filter_entry(
                    f"Allow router management from {iface}",
                    f"mtk-auto allow management {iface}",
                    chain="input",
                    **{"in-interface": iface, "action": "accept"},
                )
            )

    if rules.input_port_scan_guard:
        entries.append(
            _filter_entry(
                "Drop WAN port scans",
                "mtk-auto port scan guard",
                chain="input",
                protocol="tcp",
                **{
                    "in-interface": wan_iface,
                    "psd": "21,3s,3,1",
                    "action": "drop",
                },
            )
        )

    if rules.input_bruteforce_guard:
        entries.append(
            _filter_entry(
                "Protect SSH from WAN brute force",
                "mtk-auto ssh brute force guard",
                chain="input",
                protocol="tcp",
                **{
                    "in-interface": wan_iface,
                    "dst-port": "22",
                    "connection-limit": "3,32",
                    "action": "drop",
                },
            )
        )

    if rules.log_wan_drops:
        entries.append(
            _filter_entry(
                "Log WAN input drops",
                "mtk-auto log wan input",
                chain="input",
                **{
                    "in-interface": wan_iface,
                    "action": "log",
                    "log-prefix": "FW-IN ",
                },
            )
        )
        entries.append(
            _filter_entry(
                "Log new WAN forward attempts",
                "mtk-auto log wan forward",
                chain="forward",
                **{
                    "in-interface": wan_iface,
                    "connection-state": "new",
                    "action": "log",
                    "log-prefix": "FW-FWD ",
                },
            )
        )

    if rules.input_drop_wan_admin:
        entries.append(
            _filter_entry(
                "Drop WAN access to router",
                "mtk-auto drop wan input",
                chain="input",
                **{"in-interface": wan_iface, "action": "drop"},
            )
        )

    if rules.forward_allow_internal_to_wan:
        for iface in internal_ifaces:
            entries.append(
                _filter_entry(
                    f"Allow {iface} to WAN",
                    f"mtk-auto allow wan from {iface}",
                    chain="forward",
                    **{
                        "in-interface": iface,
                        "out-interface": wan_iface,
                        "action": "accept",
                    },
                )
            )

    if rules.forward_allow_dstnat:
        entries.append(
            _filter_entry(
                "Allow dstnat forward",
                "mtk-auto allow dstnat",
                chain="forward",
                **{
                    "in-interface": wan_iface,
                    "connection-nat-state": "dstnat",
                    "action": "accept",
                },
            )
        )

    if rules.forward_isolate_vlans:
        for source, target in _internal_pairs(internal_ifaces):
            entries.append(
                _filter_entry(
                    f"Isolate {source} from {target}",
                    f"mtk-auto isolate {source} to {target}",
                    chain="forward",
                    **{
                        "in-interface": source,
                        "out-interface": target,
                        "action": "drop",
                    },
                )
            )

    if rules.forward_drop_new_wan:
        entries.append(
            _filter_entry(
                "Drop new WAN forward",
                "mtk-auto drop new wan forward",
                chain="forward",
                **{
                    "in-interface": wan_iface,
                    "connection-state": "new",
                    "connection-nat-state": "!dstnat",
                    "action": "drop",
                },
            )
        )

    if rules.nat_masquerade:
        entries.append(
            FirewallEntry(
                section="nat",
                label="Add NAT masquerade",
                comment="mtk-auto nat masquerade",
                params={
                    "chain": "srcnat",
                    "out-interface": wan_iface,
                    "action": "masquerade",
                },
            )
        )

    if rules.raw_block_dns_wan and version_folder == "v7":
        entries.append(
            FirewallEntry(
                section="raw",
                label="Block WAN DNS early (UDP)",
                comment="mtk-auto raw dns udp",
                params={
                    "chain": "prerouting",
                    "in-interface": wan_iface,
                    "protocol": "udp",
                    "dst-port": "53",
                    "action": "drop",
                },
            )
        )
        entries.append(
            FirewallEntry(
                section="raw",
                label="Block WAN DNS early (TCP)",
                comment="mtk-auto raw dns tcp",
                params={
                    "chain": "prerouting",
                    "in-interface": wan_iface,
                    "protocol": "tcp",
                    "dst-port": "53",
                    "action": "drop",
                },
            )
        )

    return entries


def render_firewall_script(state: AppState, version_folder: str) -> str:
    entries = build_firewall_entries(state, version_folder)
    sections: list[str] = []

    for section_name, menu_path in (
        ("filter", "/ip firewall filter"),
        ("nat", "/ip firewall nat"),
        ("raw", "/ip firewall raw"),
    ):
        lines = [
            "add " + _format_params({**entry.params, "comment": entry.comment})
            for entry in entries
            if entry.section == section_name
        ]
        if lines:
            sections.append(menu_path + "\n" + "\n".join(lines))

    return "\n\n".join(sections)


def _filter_entry(label: str, comment: str, **params: Any) -> FirewallEntry:
    return FirewallEntry(section="filter", label=label, comment=comment, params=params)


def _internal_interfaces(state: AppState) -> list[str]:
    names: list[str] = []
    if state.bridge.name and (state.get_lan_interfaces() or state.vlans):
        names.append(state.bridge.name)
    names.extend(vlan.interface_name for vlan in state.vlans)
    return names


def _internal_pairs(interfaces: list[str]) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for source in interfaces:
        for target in interfaces:
            if source != target:
                pairs.append((source, target))
    return pairs


def _format_params(params: dict[str, Any]) -> str:
    return " ".join(f"{key}={_format_value(value)}" for key, value in params.items())


def _format_value(value: Any) -> str:
    if isinstance(value, bool):
        return "yes" if value else "no"
    text = str(value)
    if any(char.isspace() for char in text) or '"' in text:
        escaped = text.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return text
